---
name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  quality:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-go-quality.yaml@main
    secrets: inherit
    permissions:
      security-events: write
  docker-build:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-docker-build.yaml@main
    needs: quality
  docker-release:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/push-docker-release.yaml@main
    needs: docker-build
    permissions:
      id-token: write # This is required for requesting the JWT
      packages: write
    with:
      release: latest
      use-prebuilt-image: true
      enable-signing: true
